// Automatically generated by scripts/build-config.js at build time.
window.HireVisionConfig = {
    apiBaseUrl: "https://ai-interview-simulator-12.onrender.com/api",
    socketUrl: "https://ai-interview-simulator-12.onrender.com"
};
