services:
  - type: web
    name: hirevision-backend
    env: python
    rootDir: backend
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --threads 50 -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
