services:
  - type: web
    name: hirevision-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: hirevision-backend
          envVarKey: RENDER_PORT
      - key: FRONTEND_ORIGINS
        value: "*"
    autoDeploy: true
