const fs = require('fs');
const path = require('path');

const apiBaseUrl = process.env.API_URL || '';
const socketUrl = process.env.SOCKET_URL || '';

const configContent = `// Automatically generated by scripts/build-config.js at build time.
window.HireVisionConfig = {
    apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
    socketUrl: ${JSON.stringify(socketUrl)}
};
`;

const outputPath = path.join(__dirname, '..', 'frontend', 'config.js');

try {
    fs.writeFileSync(outputPath, configContent, 'utf8');
    console.log(`Successfully generated config.js at: ${outputPath}`);
    console.log(`API_URL set to: "${apiBaseUrl}"`);
    console.log(`SOCKET_URL set to: "${socketUrl}"`);
} catch (error) {
    console.error('Error generating config.js:', error);
    process.exit(1);
}
